
.PHONY: all say_hello generate clean

all: say_hello generate

say_hello:
	@echo "Hello World"

generate:
	@echo "Creating empty file..."
	@touch file-{1..10}.txt

clean:
	@echo "Cleaning up..."
	@rm *.txt

